### ISSUE TITLE
provide steps for contributors

### ISSUE THREAD

**Issue by DanielRuf** [Yara-Rules/blog#2]
https://github.com/Yara-Rules/blog/blob/master/README.md

So far I have not found the needed steps to generate the blog on my local computer. I just found out that this site is built with Hugo.

**Comment by Xumeiquer** [comment]
This is the public content of the blog so there is no need to build because it is already built.

In any case you can browse the content by lunching `python -m SimpleHTTPServer` or `python3 -m http.server` for instance.

**Comment by DanielRuf** [comment]
So where can we find the source if we want to contribute?

**Comment by Xumeiquer** [comment]
In which terms would you like to contribute? Do you want to write a post or something?

**Comment by DanielRuf** [comment]
Not sure how the hostname issue was fixed but when we would know the needed steps we can improve the blog and propose new content.

**Comment by Xumeiquer** [comment]
As you mentioned the blog is built with Hugo so I updated the base url, that's it.

If you want to contribute to the blog first create an issue with your proposal and we will see what is the best way to merge your contribution.

**Comment by DanielRuf** [comment]
Well I still do not know where the source files of the blog entries are so I can not propose any PRs =(

**Comment by Xumeiquer** [comment]
There is no need to know the source code of the blog, if you want to contribute write an issue telling us which will be your contribution (web rework, blog post, whatever...) and we will see which is the best way to add your work.
