### ISSUE TITLE
yararules.com now parked

### ISSUE THREAD

**Issue by RandomRhythm** [Yara-Rules/blog#4]
yararules.com no longer hosts the blog content and is now a parked domain. Whois:

Domain ID: 2589101540_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namebright.com
   Registrar URL: http://www.DropCatch1274.com
   Updated Date: 2021-02-08T05:24:03Z
   Creation Date: 2021-02-03T19:22:47Z
   Registry Expiry Date: 2022-02-03T19:22:47Z
   Registrar: DropCatch.com 1274 LLC
   Registrar IANA ID: 3483
   Registrar Abuse Contact Email:
   Registrar Abuse Contact Phone:
   Domain Status: ok https://icann.org/epp#ok
   Name Server: NS1.PARKLOGIC.COM
   Name Server: NS2.PARKLOGIC.COM

**Comment by Xumeiquer** [comment]
Yara Rules does not own that domain anymore. Instead, we are going to use https://yara-rules.github.io/blog/.

**Comment by RandomRhythm** [comment]
Gotcha, can I suggest that the URL provided at the top of the profile page (https://github.com/yara-rules/) be updated to the new domain?

**Comment by Xumeiquer** [comment]
Done!

Thank you. We have configured the old URL in several places.
